# Generated by Django 4.1.4 on 2022-12-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='user_id',
            new_name='user',
        ),
    ]
