# Generated by Django 4.1.4 on 2022-12-30 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_matches_unique_together_matches_refree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='line1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line1', to='matches.refrees'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='line2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.refrees'),
        ),
        migrations.AlterField(
            model_name='matches',
            name='refree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refree', to='matches.refrees'),
        ),
        migrations.AlterField(
            model_name='refrees',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
