# Generated by Django 4.1.4 on 2022-12-26 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('name', models.CharField(default='sub_stadium', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('rows', models.SmallIntegerField(default=7)),
                ('seats_per_row', models.SmallIntegerField(default=7)),
                ('link', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='refrees',
            name='name',
            field=models.CharField(default='sub_refree', max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('a_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.teams')),
                ('h_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h_team', to='matches.teams')),
                ('line1', models.ForeignKey(default='sub_refree1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='line1', to='matches.refrees')),
                ('line2', models.ForeignKey(default='sub_refree2', on_delete=django.db.models.deletion.SET_DEFAULT, to='matches.refrees')),
                ('ref', models.ForeignKey(default='sub_refree', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='ref', to='matches.refrees')),
                ('stadium', models.ForeignKey(default='sub_stadium', on_delete=django.db.models.deletion.SET_DEFAULT, to='matches.stadiums')),
            ],
            options={
                'unique_together': {('h_team', 'a_team', 'stadium', 'date', 'time', 'ref', 'line1', 'line2')},
            },
        ),
    ]
