# Generated by Django 4.1.4 on 2022-12-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_rename_match_id_tickets_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
