# Generated by Django 4.1.4 on 2022-12-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_matches_unique_together_matches_stage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matches',
            name='refree',
            field=models.ForeignKey(default='sub_refree', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='refree', to='matches.refrees'),
        ),
        migrations.AlterUniqueTogether(
            name='matches',
            unique_together={('h_team', 'a_team', 'stadium', 'date', 'time', 'stage', 'refree', 'line1', 'line2')},
        ),
        migrations.RemoveField(
            model_name='matches',
            name='ref',
        ),
    ]
