# Generated by Django 4.1.4 on 2022-12-31 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_matches_line1_alter_matches_line2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matches',
            options={'ordering': ['date', 'time']},
        ),
    ]
