# Generated by Django 4.1.4 on 2023-01-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_tickets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
