# Generated by Django 4.1.4 on 2023-01-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_alter_tickets_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickets',
            old_name='status',
            new_name='seat_status',
        ),
    ]
