# Generated by Django 4.1.4 on 2022-12-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Nationality',
            new_name='nationality',
        ),
    ]
