# Generated by Django 4.1.4 on 2023-01-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Egyptian', max_length=255, null=True),
        ),
    ]
